apiVersion: batch/v1
kind: Job
metadata:
  name: pi-2000
  namespace: basic-sched
spec:
  completions: 1000
  parallelism: 1000
  template:
    spec:
      #affinity:
        #nodeAffinity:
          #requiredDuringSchedulingIgnoredDuringExecution:
            #nodeSelectorTerms:
              #- matchExpressions:
                  #- key: kubernetes.io/hostname # Or your custom label, e.g., "my-node-type"
                    #operator: NotIn
                    #values:
                      #- dev-k8s-lc869-00
                      #- dev-k8s-lc869-01
      schedulerName:
      #nodeName: dev-k8s-lc869-01
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "500m"
      restartPolicy: Never
      imagePullSecrets:
      - name: regcred
  backoffLimit: 4
