apiVersion: v1
kind: ServiceAccount
metadata:
  name: remote-sched-account
  namespace: basic-sched
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: remote-sched-as-admin-user
subjects:
- kind: ServiceAccount
  name: remote-sched-account
  namespace: basic-sched
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

